### ISSUE TITLE
Compact mode for sub level of bullet

### ISSUE THREAD

**Issue by zackles** [vanchKong/layout-plugin#1]
Hello,
Good job! I needed a pluging like that for bullet.

It works well for bullet but only for the first level.
Second level bullet and beyond stay with big lining space
![image](https://github.com/vanchKong/layout-plugin/assets/11263148/bfe61884-eecc-4da8-a152-73972e2ca4f8)

**Comment by vanchKong** [comment]
Thanks for your feedback, it's Done!
But may have to wait for Siyuan to pull my distribution. [v0.0.2](https://github.com/vanchKong/layout-plugin/releases/tag/v0.0.2)

**Comment by zackles** [comment]
Thanks, you are quick!
